### ISSUE TITLE
[TechnicalTask] config.yaml: データマッピングルール設定機能の実装 (TASK-CONFIG-DATAMAP-RULES)

### ISSUE THREAD

**Issue by masa-codehub** [masa-codehub/github-auto-setup#118]
**Content:**
`config.yaml`に、ユーザーがAIのデータマッピングを補助するためのルールを記述できるセクションを追加し、その設定を読み込んでマッピング処理に反映させる機能を実装する。
ルール形式の例:
```yaml
data_mapping_rules:
  common: # 全ファイル形式共通のヒント
    title_keys: ["title", "Subject", "件名"]
    description_keys: ["description", "body", "詳細", "内容"]
  yaml: # YAML特有のルール
    issues_list_path: "issues" # ルートからのJMESPath/JSONPath類似表現
    field_mappings: # issues_list_path内の各要素からの相対パス
      title: "title"
      description: "details.summary" # ネストされたキーにも対応
      labels: "metadata.tags"
```

**Implementation Tasks:**
- [ ] `config.yaml`のスキーマ（Pydanticモデル `Settings`）に`data_mapping_rules`セクションを追加
- [ ] 設定読み込み処理 (`config.py`)でマッピングルールをパースし、`Settings`オブジェクト経由で利用可能にする
- [ ] `AIParser`（または`IssueFileInterpreter`）が、これらのルールをAIへのプロンプト生成時のヒントとして利用する、またはAIの推論結果をルールに基づいて上書き/補正するロジックを実装
- **テスト:**
  - [ ] （TDD）マッピングルール設定の読み込みとパース処理のユニットテスト
  - [ ] （TDD）AIマッピングロジックが、設定されたルールを正しく解釈し、マッピング結果に反映することを検証するユニットテスト (TASK-DATAMAP-IMPLのテストと連携)

**Action/Verification:**
設計したルールフォーマットで`config.yaml`にルールを記述し、それがAIマッピング処理に正しく反映されることをユニットテストで確認。

**Referenced Requirements:**
- 11. 制約条件・前提条件 (データマッピングルールの設定)
- 2. システムが満たすべき主要な成功基準 (機能: 柔軟性)

**Dependencies:**
- TASK-DATAMAP-IMPL (AIマッピングロジックの基本実装が必要)

**Size Estimate:** [SP: 5]
